version: '3'

services:
  chroma:
    build: ../database/.
    ports:
      - 8000:8000

  web:
    build: .
    command: sh -c "sleep 10 && uvicorn main:app --reload --port=8080 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - chroma