version: '3'

services:
  chroma:
    image: chromadb/chroma
    ports:
      - 8000:8000
    volumes:
      - /tmp/rando_data:/chroma/chroma

  web:
    build: .
    command: sh -c "sleep 10 && uvicorn main:app --reload --port=8080 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - chroma