name: Deploy Telegram Bot to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Container Registry
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build, Push and Release Docker container to Heroku 
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./telegram-bot
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
