name: Deploy Telegram Bot to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Login to Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Check if Heroku app exists
        id: check_app
        run: |
          if heroku apps:info echofinder-telegram > /dev/null 2>&1; then
            echo "App exists"
            echo "::set-output name=exists::true"
          else
            echo "App does not exist"
            echo "::set-output name=exists::false"
          fi
        env:
          HEROKU_APP_NAME: echofinder-telegram
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Create Heroku app
        if: steps.check_app.outputs.exists == 'false'
        run: heroku apps:create echofinder-telegram
        env:
          HEROKU_APP_NAME: echofinder-telegram
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build Docker image
        run: cd telegram-bot && docker build -t registry.heroku.com/echofinder-telegram/web .

      - name: Push Docker image to Heroku Container Registry
        run: cd telegram-bot && docker push registry.heroku.com/echofinder-telegram/web

      - name: Set environment variables
        run: cd telegram-bot && heroku config:set TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} NODE_ENV=${{ env.NODE_ENV }} BACKEND_HOST=${{ env.BACKEND_HOST }} BACKEND_PORT=${{ env.BACKEND_PORT }} BACKEND_API_KEY=${{ secrets.BACKEND_API_KEY }} API_CLIENT_TIMEOUT=${{ env.API_CLIENT_TIMEOUT }} PLATFORM=${{ env.PLATFORM }} --app echofinder-telegram
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release Docker image on Heroku
        run: cd telegram-bot && heroku container:release web --app echofinder-telegram
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
