name: Deploy Telegram Bot to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Heroku Container Registry
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build Docker image
        run: cd telegram-bot && docker build -t registry.heroku.com/echofinder-telegram/web .

      - name: Push Docker image to Heroku Container Registry
        run: cd telegram-bot && docker push registry.heroku.com/echofinder-telegram/web

      - name: Set environment variables
        run: cd telegram-bot && heroku config:set TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} NODE_ENV=${{ env.NODE_ENV }} BACKEND_HOST=${{ env.BACKEND_HOST }} BACKEND_PORT=${{ env.BACKEND_PORT }} BACKEND_API_KEY=${{ secrets.BACKEND_API_KEY }} API_CLIENT_TIMEOUT=${{ env.API_CLIENT_TIMEOUT }} PLATFORM=${{ env.PLATFORM }} --app echofinder-telegram
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release Docker image on Heroku
        run: cd telegram-bot && heroku container:release web --app echofinder-telegram
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
